# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_des.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(611, 681)
        Form.setStyleSheet("background-color: rgba(135, 217, 255,190);\n"
"")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 620, 491, 51))
        self.textBrowser.setStyleSheet("background-color: rgba(80, 46, 122, 120);\n"
"font: 63 15pt \"Segoe UI Semibold\";\n"
"border-radius:15px;\n"
"color: rgb(221, 221, 221);")
        self.textBrowser.setUndoRedoEnabled(True)
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(510, 627, 93, 41))
        self.pushButton.setStyleSheet("background-color: rgba(80, 177, 137, 160);\n"
"border-radius:10px;\n"
"font: 75 14pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 591, 601))
        self.listWidget.setStyleSheet("background-color: rgba(51, 49, 122,150);\n"
"border-radius:15px;\n"
"font: 63 15pt \"Segoe UI Semibold\";\n"
"border-radius:15px;\n"
"color: rgb(221, 221, 221);")
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Ask"))
